# CMake generated Testfile for 
# Source directory: /home/p4/src/behavioral-model/targets/psa_switch_grpc/tests
# Build directory: /home/p4/src/behavioral-model/targets/psa_switch_grpc/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Uu][Nn]_[Ss][Oo][Ll][Oo])$")
  add_test(psa_switch_grpc/psa_test_basic "psa_test_basic")
  set_tests_properties(psa_switch_grpc/psa_test_basic PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/targets/psa_switch_grpc/tests/CMakeLists.txt;71;add_test;/home/p4/src/behavioral-model/targets/psa_switch_grpc/tests/CMakeLists.txt;0;")
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Uu][Nn]_[Ss][Oo][Ll][Oo])$")
  add_test(psa_switch_grpc/psa_test_grpc_dp "psa_test_grpc_dp")
  set_tests_properties(psa_switch_grpc/psa_test_grpc_dp PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/targets/psa_switch_grpc/tests/CMakeLists.txt;71;add_test;/home/p4/src/behavioral-model/targets/psa_switch_grpc/tests/CMakeLists.txt;0;")
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Uu][Nn]_[Ss][Oo][Ll][Oo])$")
  add_test(psa_switch_grpc/psa_test_packet_io "psa_test_packet_io")
  set_tests_properties(psa_switch_grpc/psa_test_packet_io PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/targets/psa_switch_grpc/tests/CMakeLists.txt;71;add_test;/home/p4/src/behavioral-model/targets/psa_switch_grpc/tests/CMakeLists.txt;0;")
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Uu][Nn]_[Ss][Oo][Ll][Oo])$")
  add_test(psa_switch_grpc/psa_test_counter "psa_test_counter")
  set_tests_properties(psa_switch_grpc/psa_test_counter PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/targets/psa_switch_grpc/tests/CMakeLists.txt;71;add_test;/home/p4/src/behavioral-model/targets/psa_switch_grpc/tests/CMakeLists.txt;0;")
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Uu][Nn]_[Ss][Oo][Ll][Oo])$")
  add_test(psa_switch_grpc/psa_test_meter "psa_test_meter")
  set_tests_properties(psa_switch_grpc/psa_test_meter PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/targets/psa_switch_grpc/tests/CMakeLists.txt;71;add_test;/home/p4/src/behavioral-model/targets/psa_switch_grpc/tests/CMakeLists.txt;0;")
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Uu][Nn]_[Ss][Oo][Ll][Oo])$")
  add_test(psa_switch_grpc/psa_test_ternary "psa_test_ternary")
  set_tests_properties(psa_switch_grpc/psa_test_ternary PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/targets/psa_switch_grpc/tests/CMakeLists.txt;71;add_test;/home/p4/src/behavioral-model/targets/psa_switch_grpc/tests/CMakeLists.txt;0;")
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Uu][Nn]_[Ss][Oo][Ll][Oo])$")
  add_test(psa_switch_grpc/psa_test_pre "psa_test_pre")
  set_tests_properties(psa_switch_grpc/psa_test_pre PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/targets/psa_switch_grpc/tests/CMakeLists.txt;71;add_test;/home/p4/src/behavioral-model/targets/psa_switch_grpc/tests/CMakeLists.txt;0;")
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Uu][Nn]_[Ss][Oo][Ll][Oo])$")
  add_test(psa_switch_grpc/psa_test_digest "psa_test_digest")
  set_tests_properties(psa_switch_grpc/psa_test_digest PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/targets/psa_switch_grpc/tests/CMakeLists.txt;71;add_test;/home/p4/src/behavioral-model/targets/psa_switch_grpc/tests/CMakeLists.txt;0;")
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Uu][Nn]_[Ss][Oo][Ll][Oo])$")
  add_test(psa_switch_grpc/psa_test_idle_timeout "psa_test_idle_timeout")
  set_tests_properties(psa_switch_grpc/psa_test_idle_timeout PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/targets/psa_switch_grpc/tests/CMakeLists.txt;71;add_test;/home/p4/src/behavioral-model/targets/psa_switch_grpc/tests/CMakeLists.txt;0;")
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Uu][Nn]_[Ss][Oo][Ll][Oo])$")
  add_test(psa_switch_grpc/psa_test_action_profile "psa_test_action_profile")
  set_tests_properties(psa_switch_grpc/psa_test_action_profile PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/targets/psa_switch_grpc/tests/CMakeLists.txt;71;add_test;/home/p4/src/behavioral-model/targets/psa_switch_grpc/tests/CMakeLists.txt;0;")
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Uu][Nn]_[Ss][Oo][Ll][Oo])$")
  add_test(psa_switch_grpc/psa_test_optional "psa_test_optional")
  set_tests_properties(psa_switch_grpc/psa_test_optional PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/targets/psa_switch_grpc/tests/CMakeLists.txt;71;add_test;/home/p4/src/behavioral-model/targets/psa_switch_grpc/tests/CMakeLists.txt;0;")
endif()
