# SPDX-FileCopyrightText: 2023 Antonin Bas
#
# SPDX-License-Identifier: Apache-2.0

version: 2
updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
