/*
 * SPDX-FileCopyrightText: 2013 Barefoot Networks, Inc.
 * Copyright 2013-present Barefoot Networks, Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Antonin Bas (antonin@barefootnetworks.com)
 *
 */

//! @file event_logger.h

#ifndef BM_BM_SIM_EVENT_LOGGER_H_
#define BM_BM_SIM_EVENT_LOGGER_H_

#include <bm/config.h>

#include <memory>
#include <string>
#include <utility>

#include "device_id.h"
#include "event_observer.h"
#include "phv_forward.h"
#include "transport.h"

namespace bm {

//! Signals significant packet event by publishing a message on a
//! transport. This is meant to be used with the nanomsg PUB/SUB transport.
//! Other processes can subscribe to the channel to monitor the activity of the
//! switch (e.g. for logging). So far, we are mostly using this for the
//! end-to-end testing of target switch implementations. Note that depending on
//! the transport, some messages can be lost (the nanomsg PUB/SUB transport does
//! not guarantee delivery to all subscribers, and message drops will happen if
//! a subscriber is slower than the producer).
//!
//! Most messages are generated by the bmv2 code, but the target is for now
//! responsible of generated "packet in" and "packet out" messages (when a
//! packet is received / transmitted). Obviously, this is optional and you do
//! not have to do it if you are not interested in using the event logger.
class EventLogger : public EventObserverIface {
 public:
  explicit EventLogger(std::unique_ptr<TransportIface> transport,
                       device_id_t device_id = 0)
      : transport_instance(std::move(transport)), device_id(device_id) { }

  void packet_in(const Packet& packet) override;
  void packet_out(const Packet& packet) override;

  void parser_start(const Packet& packet, const Parser& parser) override;
  void parser_done(const Packet& packet, const Parser& parser) override;
  void parser_extract(const Packet& packet, header_id_t header) override;

  void deparser_start(const Packet& packet, const Deparser& deparser) override;
  void deparser_done(const Packet& packet, const Deparser& deparser) override;
  void deparser_emit(const Packet& packet, header_id_t header) override;

  void checksum_update(const Packet& packet, const Checksum& checksum) override;

  void pipeline_start(const Packet& packet, const Pipeline& pipeline) override;
  void pipeline_done(const Packet& packet, const Pipeline& pipeline) override;

  void condition_eval(const Packet& packet, const Conditional& cond,
                      bool result) override;
  void table_hit(const Packet& packet, const MatchTableAbstract& table,
                 entry_handle_t handle) override;
  void table_miss(const Packet& packet,
                  const MatchTableAbstract& table) override;

  void action_execute(const Packet& packet, const ActionFn& action_fn,
                      const ActionData& action_data) override;

  void config_change() override;

  static EventLogger *get() {
    static EventLogger event_logger(TransportIface::make_dummy());
    return &event_logger;
  }

  static void init(std::unique_ptr<TransportIface> transport,
                   device_id_t device_id = 0) {
    get()->transport_instance = std::move(transport);
    get()->device_id = device_id;
    EventObserverRegistry::get()->register_observer(get());
  }

 private:
  std::unique_ptr<TransportIface> transport_instance{nullptr};
  device_id_t device_id{};
};

}  // namespace bm

#endif  // BM_BM_SIM_EVENT_LOGGER_H_
