/*
 * SPDX-FileCopyrightText: 2013 Barefoot Networks, Inc.
 * Copyright 2013-present Barefoot Networks, Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Antonin Bas (antonin@barefootnetworks.com)
 *
 */

#ifndef BM_BM_SIM_MATCH_ERROR_CODES_H_
#define BM_BM_SIM_MATCH_ERROR_CODES_H_

namespace bm {

enum class MatchErrorCode {
  SUCCESS = 0,
  TABLE_FULL,
  INVALID_HANDLE,
  EXPIRED_HANDLE,
  COUNTERS_DISABLED,
  METERS_DISABLED,
  AGEING_DISABLED,
  INVALID_TABLE_NAME,
  INVALID_ACTION_NAME,
  WRONG_TABLE_TYPE,
  INVALID_MBR_HANDLE,
  MBR_STILL_USED,
  MBR_ALREADY_IN_GRP,
  MBR_NOT_IN_GRP,
  INVALID_GRP_HANDLE,
  GRP_STILL_USED,
  EMPTY_GRP,
  DUPLICATE_ENTRY,
  BAD_MATCH_KEY,
  INVALID_METER_OPERATION,
  DEFAULT_ACTION_IS_CONST,
  DEFAULT_ENTRY_IS_CONST,
  NO_DEFAULT_ENTRY,
  INVALID_ACTION_PROFILE_NAME,
  NO_ACTION_PROFILE_SELECTION,
  IMMUTABLE_TABLE_ENTRIES,
  BAD_ACTION_DATA,
  NO_TABLE_KEY,
  ERROR,
};

const char *match_error_code_to_string(MatchErrorCode code);

}  // namespace bm

#endif  // BM_BM_SIM_MATCH_ERROR_CODES_H_
