# Config file for automatic testing at travis-ci.org

sudo: required

language: cpp

addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - libjudy-dev
      - libgmp-dev
      - libpcap-dev
      - libboost1.55-dev
      - libboost-test1.55-dev
      - libboost-program-options1.55-dev
      - libboost-system1.55-dev
      - libboost-filesystem1.55-dev
      - libboost-thread1.55-dev
      - libevent-dev
      - automake
      - libtool
      - flex 
      - bison
      - pkg-config
      - g++-4.8
      - libssl-dev

before_install:
  - g++ -v
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 99
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.8 99
  - g++ -v
  - wget https://s3-us-west-2.amazonaws.com/p4lang/thrift_bin.tar.gz
  - tar -xzvf thrift_bin.tar.gz -C $HOME/
  - export PATH=$PATH:$HOME/thrift/bin/
  - export LDFLAGS="$LDFLAGS -L$HOME/thrift/lib"
  - export CPPFLAGS="$CPPFLAGS -I$HOME/thrift/include"
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/thrift/lib
  - bash build/travis/install-nanomsg.sh
  - sudo ldconfig
  - bash build/travis/install-nnpy.sh

install:
  - ./autogen.sh && ./configure --enable-coverage && make all -j2

# command to run tests, e.g. python setup.py test
script:
  - python build/travis/check-nnpy.py
  - make check
  - bash tools/check_style.sh

# code coverage
after_success:
  - cd modules/bm_sim/src; gcov -r -o .libs/ *.cpp; cd -
  - bash <(curl -s https://codecov.io/bash)
