# Config file for automatic testing at travis-ci.org

sudo: required

dist: trusty

language: generic

services:
  - docker

matrix:
  include:
    - env: CXX=g++ CC=gcc sswitch_grpc=yes
    - env: CXX=g++-7 CC=gcc-7 GCOV=gcov-7 sswitch_grpc=no
    - env: CXX=clang++-3.8 CC=clang-3.8 sswitch_grpc=no
    - env: CXX=clang++-6.0 CC=clang-6.0 sswitch_grpc=no

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-xenial-6.0

install:
  - docker build -t bm --build-arg IMAGE_TYPE=test --build-arg CC=$CC --build-arg CXX=$CXX --build-arg GCOV=$GCOV --build-arg sswitch_grpc=$sswitch_grpc .

script:
  - ci_env=`bash <(curl -s https://codecov.io/env)`
  - docker run $ci_env --env GCOV -w /behavioral-model bm /bin/bash -c "make check -j2 && ./travis/codecov.sh"
  - if [ "$sswitch_grpc" = "yes" ]; then docker run -w /behavioral-model/targets/simple_switch_grpc bm make check -j2; fi
  - bash tools/check_style.sh
