# Config file for automatic testing at travis-ci.org

sudo: required

dist: trusty

language: generic

services:
  - docker

matrix:
  include:
    - env: CXX=g++ CC=gcc
    - env: CXX=g++-6 CC=gcc-6 GCOV=gcov-6
    - env: CXX=clang++-3.8 CC=clang-3.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

install:
  - docker build -t bm --build-arg IMAGE_TYPE=test --build-arg CC=$CC --build-arg CXX=$CXX --build-arg GCOV=$GCOV .

script:
  - docker run -w /behavioral-model bm make check -j2
  - bash tools/check_style.sh

# code coverage
after_success:
  - ci_env=`bash <(curl -s https://codecov.io/env)`
  - if [ "$GCOV" != "" ]; then docker run -w /behavioral-model bm $ci_env bash -c "cd src/bm_sim; $GCOV -p -r -o .libs/ *.cpp; rm *third_party*; bash <(curl -s https://codecov.io/bash) -x $GCOV -p src/bm_sim"; fi
