# Config file for automatic testing at travis-ci.org

sudo: required

language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      env: COMPILER=g++-4.8 GCOV=gcov-4.8

    - os: linux
      compiler: gcc
      env: COMPILER=g++-5 GCOV=gcov-5

addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - libjudy-dev
      - libgmp-dev
      - libpcap-dev
      - libboost1.55-dev
      - libboost-test1.55-dev
      - libboost-program-options1.55-dev
      - libboost-system1.55-dev
      - libboost-filesystem1.55-dev
      - libboost-thread1.55-dev
      - libevent-dev
      - automake
      - libtool
      - flex 
      - bison
      - pkg-config
      - g++-4.8
      - g++-5
      - libssl-dev
      - python-pip

before_install:
  - wget https://s3-us-west-2.amazonaws.com/p4lang/thrift_bin.tar.gz
  - tar -xzvf thrift_bin.tar.gz -C $HOME/
  - export PATH=$PATH:$HOME/thrift/bin/
  - export LDFLAGS="$LDFLAGS -L$HOME/thrift/lib"
  - export CPPFLAGS="$CPPFLAGS -I$HOME/thrift/include"
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/thrift/lib
  - sudo pip install --upgrade thrift
  - bash travis/install-nanomsg.sh
  - sudo ldconfig
  - bash travis/install-nnpy.sh

install:
  - ./autogen.sh
  - if [ "$GCOV" != "" ]; then ./configure CXX=$COMPILER --with-pdfixed --with-stress-tests --enable-coverage; fi
  - if [ "$GCOV" = "" ]; then ./configure CXX=$COMPILER --with-pdfixed --with-stress-tests; fi
  - make all -j2

# command to run tests, e.g. python setup.py test
script:
  - python travis/check-nnpy.py
  - make check
  - bash tools/check_style.sh

# code coverage
after_success:
  - if [ "$GCOV" != "" ]; then (cd src/bm_sim; $GCOV -r -o .libs/ *.cpp); fi
  - if [ "$GCOV" != "" ]; then bash <(curl -s https://codecov.io/bash); fi
