# Config file for automatic testing at travis-ci.org

sudo: required

dist: trusty

language: generic

services:
  - docker

matrix:
  include:
    - env: CXX=g++ CC=gcc
    - env: CXX=g++-6 CC=gcc-6 GCOV=gcov-6
    - env: CXX=clang++-3.8 CC=clang-3.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

install:
  - docker build -t bm --build-arg IMAGE_TYPE=test --build-arg CC=$CC --build-arg CXX=$CXX --build-arg GCOV=$GCOV .

script:
  - ci_env=`bash <(curl -s https://codecov.io/env)`
  - docker run $ci_env --env GCOV -w /behavioral-model bm /bin/bash -c "make check -j2 && ./travis/codecov.sh"
  - bash tools/check_style.sh
