# SPDX-FileCopyrightText: 2017 Barefoot Networks, Inc.
#
# SPDX-License-Identifier: Apache-2.0

FROM p4lang/third-party:latest
LABEL maintainer="P4 Developers <p4-dev@lists.p4.org>"
LABEL description="This Docker image does not have any dependency on PI or P4 \
Runtime, it only builds bmv2 simple_switch."

# Select the type of image we're building. Use `build` for a normal build, which
# is optimized for image size. Use `test` if this image will be used for
# testing; in this case, the source code and build-only dependencies will not be
# removed from the image.
ARG IMAGE_TYPE=build
ENV BM_DEPS build-essential \
            pkg-config \
            cmake \
            curl \
            git \
            libgmp-dev \
            libpcap-dev \
            libboost-dev \
            libboost-program-options-dev \
            libboost-system-dev \
            libboost-filesystem-dev \
            libboost-thread-dev \
            libjsoncpp-dev \
            libxxhash-dev
ENV BM_RUNTIME_DEPS libboost-program-options1.83.0 \
                    libboost-system1.83.0 \
                    libboost-filesystem1.83.0 \
                    libboost-thread1.83.0 \
                    libgmp10 \
                    libpcap0.8t64 \
                    libjsoncpp25 \
                    libxxhash0 \
                    python3 \
                    python3-six \
                    python-is-python3

COPY . /behavioral-model/
WORKDIR /behavioral-model/
RUN apt-get update -qq
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata
RUN apt-get install -qq --no-install-recommends build-essential
RUN apt-get install -qq --no-install-recommends pkg-config
RUN apt-get install -qq --no-install-recommends cmake
RUN apt-get install -qq --no-install-recommends curl
RUN apt-get install -qq --no-install-recommends git
RUN apt-get install -qq --no-install-recommends libgmp-dev
RUN apt-get install -qq --no-install-recommends libpcap-dev
RUN apt-get install -qq --no-install-recommends libboost-dev
RUN apt-get install -qq --no-install-recommends libboost-program-options-dev
RUN apt-get install -qq --no-install-recommends libboost-system-dev
RUN apt-get install -qq --no-install-recommends libboost-filesystem-dev
RUN apt-get install -qq --no-install-recommends libboost-thread-dev
RUN apt-get install -qq --no-install-recommends libjsoncpp-dev
RUN apt-get install -qq --no-install-recommends libxxhash-dev
RUN apt-get install -qq --no-install-recommends libboost-program-options1.83.0
RUN apt-get install -qq --no-install-recommends libboost-system1.83.0
RUN apt-get install -qq --no-install-recommends libboost-filesystem1.83.0
RUN apt-get install -qq --no-install-recommends libboost-thread1.83.0
RUN apt-get install -qq --no-install-recommends libgmp10
RUN apt-get install -qq --no-install-recommends libpcap0.8t64
RUN apt-get install -qq --no-install-recommends libjsoncpp25
RUN apt-get install -qq --no-install-recommends libxxhash0
RUN apt-get install -qq --no-install-recommends python3
RUN apt-get install -qq --no-install-recommends python3-six
RUN apt-get install -qq --no-install-recommends python-is-python3

RUN mkdir -p build && cd build && \
    cmake -DENABLE_DEBUGGER=ON ..
RUN cmake --build . -j$(nproc)
RUN ctest --output-on-failure && \
    cmake --install . && cd .. && \
    ldconfig && \
    (test "$IMAGE_TYPE" = "build" && \
        apt-get purge -qq $BM_DEPS && \
        apt-get autoremove --purge -qq && \
        rm -rf /behavioral-model /var/cache/apt/* /var/lib/apt/lists/* && \
        echo 'Build image ready') || \
    (test "$IMAGE_TYPE" = "test" && \
      echo 'Test image ready')
