# CMake generated Testfile for 
# Source directory: /home/p4/src/behavioral-model/tests
# Build directory: /home/p4/src/behavioral-model/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_actions "/home/p4/src/behavioral-model/tests/test_actions")
set_tests_properties(test_actions PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/tests/CMakeLists.txt;105;add_test;/home/p4/src/behavioral-model/tests/CMakeLists.txt;0;")
add_test(test_ageing "/home/p4/src/behavioral-model/tests/test_ageing")
set_tests_properties(test_ageing PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/tests/CMakeLists.txt;105;add_test;/home/p4/src/behavioral-model/tests/CMakeLists.txt;0;")
add_test(test_assert_assume "/home/p4/src/behavioral-model/tests/test_assert_assume")
set_tests_properties(test_assert_assume PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/tests/CMakeLists.txt;105;add_test;/home/p4/src/behavioral-model/tests/CMakeLists.txt;0;")
add_test(test_bm_apps "/home/p4/src/behavioral-model/tests/test_bm_apps")
set_tests_properties(test_bm_apps PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/tests/CMakeLists.txt;105;add_test;/home/p4/src/behavioral-model/tests/CMakeLists.txt;0;")
add_test(test_calculations "/home/p4/src/behavioral-model/tests/test_calculations")
set_tests_properties(test_calculations PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/tests/CMakeLists.txt;105;add_test;/home/p4/src/behavioral-model/tests/CMakeLists.txt;0;")
add_test(test_checksums "/home/p4/src/behavioral-model/tests/test_checksums")
set_tests_properties(test_checksums PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/tests/CMakeLists.txt;105;add_test;/home/p4/src/behavioral-model/tests/CMakeLists.txt;0;")
add_test(test_conditionals "/home/p4/src/behavioral-model/tests/test_conditionals")
set_tests_properties(test_conditionals PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/tests/CMakeLists.txt;105;add_test;/home/p4/src/behavioral-model/tests/CMakeLists.txt;0;")
add_test(test_control_flow "/home/p4/src/behavioral-model/tests/test_control_flow")
set_tests_properties(test_control_flow PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/tests/CMakeLists.txt;105;add_test;/home/p4/src/behavioral-model/tests/CMakeLists.txt;0;")
add_test(test_core_primitives "/home/p4/src/behavioral-model/tests/test_core_primitives")
set_tests_properties(test_core_primitives PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/tests/CMakeLists.txt;105;add_test;/home/p4/src/behavioral-model/tests/CMakeLists.txt;0;")
add_test(test_counters "/home/p4/src/behavioral-model/tests/test_counters")
set_tests_properties(test_counters PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/tests/CMakeLists.txt;105;add_test;/home/p4/src/behavioral-model/tests/CMakeLists.txt;0;")
add_test(test_data "/home/p4/src/behavioral-model/tests/test_data")
set_tests_properties(test_data PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/tests/CMakeLists.txt;105;add_test;/home/p4/src/behavioral-model/tests/CMakeLists.txt;0;")
add_test(test_devmgr "/home/p4/src/behavioral-model/tests/test_devmgr")
set_tests_properties(test_devmgr PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/tests/CMakeLists.txt;105;add_test;/home/p4/src/behavioral-model/tests/CMakeLists.txt;0;")
add_test(test_enums "/home/p4/src/behavioral-model/tests/test_enums")
set_tests_properties(test_enums PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/tests/CMakeLists.txt;105;add_test;/home/p4/src/behavioral-model/tests/CMakeLists.txt;0;")
add_test(test_expressions "/home/p4/src/behavioral-model/tests/test_expressions")
set_tests_properties(test_expressions PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/tests/CMakeLists.txt;105;add_test;/home/p4/src/behavioral-model/tests/CMakeLists.txt;0;")
add_test(test_extern "/home/p4/src/behavioral-model/tests/test_extern")
set_tests_properties(test_extern PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/tests/CMakeLists.txt;105;add_test;/home/p4/src/behavioral-model/tests/CMakeLists.txt;0;")
add_test(test_fields "/home/p4/src/behavioral-model/tests/test_fields")
set_tests_properties(test_fields PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/tests/CMakeLists.txt;105;add_test;/home/p4/src/behavioral-model/tests/CMakeLists.txt;0;")
add_test(test_handle_mgr "/home/p4/src/behavioral-model/tests/test_handle_mgr")
set_tests_properties(test_handle_mgr PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/tests/CMakeLists.txt;105;add_test;/home/p4/src/behavioral-model/tests/CMakeLists.txt;0;")
add_test(test_header_stacks "/home/p4/src/behavioral-model/tests/test_header_stacks")
set_tests_properties(test_header_stacks PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/tests/CMakeLists.txt;105;add_test;/home/p4/src/behavioral-model/tests/CMakeLists.txt;0;")
add_test(test_header_unions "/home/p4/src/behavioral-model/tests/test_header_unions")
set_tests_properties(test_header_unions PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/tests/CMakeLists.txt;105;add_test;/home/p4/src/behavioral-model/tests/CMakeLists.txt;0;")
add_test(test_headers "/home/p4/src/behavioral-model/tests/test_headers")
set_tests_properties(test_headers PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/tests/CMakeLists.txt;105;add_test;/home/p4/src/behavioral-model/tests/CMakeLists.txt;0;")
add_test(test_learning "/home/p4/src/behavioral-model/tests/test_learning")
set_tests_properties(test_learning PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/tests/CMakeLists.txt;105;add_test;/home/p4/src/behavioral-model/tests/CMakeLists.txt;0;")
add_test(test_log_msg "/home/p4/src/behavioral-model/tests/test_log_msg")
set_tests_properties(test_log_msg PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/tests/CMakeLists.txt;105;add_test;/home/p4/src/behavioral-model/tests/CMakeLists.txt;0;")
add_test(test_meters "/home/p4/src/behavioral-model/tests/test_meters")
set_tests_properties(test_meters PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/tests/CMakeLists.txt;105;add_test;/home/p4/src/behavioral-model/tests/CMakeLists.txt;0;")
add_test(test_p4objects "/home/p4/src/behavioral-model/tests/test_p4objects")
set_tests_properties(test_p4objects PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/tests/CMakeLists.txt;105;add_test;/home/p4/src/behavioral-model/tests/CMakeLists.txt;0;")
add_test(test_packet "/home/p4/src/behavioral-model/tests/test_packet")
set_tests_properties(test_packet PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/tests/CMakeLists.txt;105;add_test;/home/p4/src/behavioral-model/tests/CMakeLists.txt;0;")
add_test(test_parser "/home/p4/src/behavioral-model/tests/test_parser")
set_tests_properties(test_parser PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/tests/CMakeLists.txt;105;add_test;/home/p4/src/behavioral-model/tests/CMakeLists.txt;0;")
add_test(test_pcap "/home/p4/src/behavioral-model/tests/test_pcap")
set_tests_properties(test_pcap PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/tests/CMakeLists.txt;105;add_test;/home/p4/src/behavioral-model/tests/CMakeLists.txt;0;")
add_test(test_periodic_tasks "/home/p4/src/behavioral-model/tests/test_periodic_tasks")
set_tests_properties(test_periodic_tasks PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/tests/CMakeLists.txt;105;add_test;/home/p4/src/behavioral-model/tests/CMakeLists.txt;0;")
add_test(test_phv "/home/p4/src/behavioral-model/tests/test_phv")
set_tests_properties(test_phv PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/tests/CMakeLists.txt;105;add_test;/home/p4/src/behavioral-model/tests/CMakeLists.txt;0;")
add_test(test_pre "/home/p4/src/behavioral-model/tests/test_pre")
set_tests_properties(test_pre PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/tests/CMakeLists.txt;105;add_test;/home/p4/src/behavioral-model/tests/CMakeLists.txt;0;")
add_test(test_queue "/home/p4/src/behavioral-model/tests/test_queue")
set_tests_properties(test_queue PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/tests/CMakeLists.txt;105;add_test;/home/p4/src/behavioral-model/tests/CMakeLists.txt;0;")
add_test(test_queueing "/home/p4/src/behavioral-model/tests/test_queueing")
set_tests_properties(test_queueing PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/tests/CMakeLists.txt;105;add_test;/home/p4/src/behavioral-model/tests/CMakeLists.txt;0;")
add_test(test_ras "/home/p4/src/behavioral-model/tests/test_ras")
set_tests_properties(test_ras PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/tests/CMakeLists.txt;105;add_test;/home/p4/src/behavioral-model/tests/CMakeLists.txt;0;")
add_test(test_runtime_iface "/home/p4/src/behavioral-model/tests/test_runtime_iface")
set_tests_properties(test_runtime_iface PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/tests/CMakeLists.txt;105;add_test;/home/p4/src/behavioral-model/tests/CMakeLists.txt;0;")
add_test(test_stateful "/home/p4/src/behavioral-model/tests/test_stateful")
set_tests_properties(test_stateful PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/tests/CMakeLists.txt;105;add_test;/home/p4/src/behavioral-model/tests/CMakeLists.txt;0;")
add_test(test_switch "/home/p4/src/behavioral-model/tests/test_switch")
set_tests_properties(test_switch PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/tests/CMakeLists.txt;105;add_test;/home/p4/src/behavioral-model/tests/CMakeLists.txt;0;")
add_test(test_tables "/home/p4/src/behavioral-model/tests/test_tables")
set_tests_properties(test_tables PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/tests/CMakeLists.txt;105;add_test;/home/p4/src/behavioral-model/tests/CMakeLists.txt;0;")
add_test(test_target_parser "/home/p4/src/behavioral-model/tests/test_target_parser")
set_tests_properties(test_target_parser PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/tests/CMakeLists.txt;105;add_test;/home/p4/src/behavioral-model/tests/CMakeLists.txt;0;")
