version: 0.8.{build}
environment:
  global:
    ASCIIDOCTOR_VER: 1.5.4
    CFLAGS: /MP
  matrix:
    # array of all environments used to test builds
    - GENERATOR: NMake Makefiles
      CFG: Debug
      VS_VERSION: 12.0
    - GENERATOR: Visual Studio 14 2015
      VS_VERSION: 14.0
      CFG: Debug
    - GENERATOR: Visual Studio 12 2013
      VS_VERSION: 12.0
      CFG: Debug
    - GENERATOR: Visual Studio 14 2015 Win64
      CFG: Debug
      VS_VERSION: 14.0
    - GENERATOR: Visual Studio 12 2013 Win64
      CFG: Debug
      VS_VERSION: 12.0

cache:
  - '%USERPROFILE%\asciidoctor-%ASCIIDOCTOR_VER%.gem -> .appveyor.yml'

install:
  # Gem fetching can sometimes be excruciatingly slow due to the rubygems database,
  # so we have to manually download our target gem.
  - ps: |
      $asciidoctor = "$($env:USERPROFILE)\asciidoctor-$($env:ASCIIDOCTOR_VER).gem"
      if (-not (Test-Path $asciidoctor)) {
          $url = "https://rubygems.org/downloads/asciidoctor-$($env:ASCIIDOCTOR_VER).gem"
          Write-Output "Downloading asciidoctor $env:ASCIIDOCTOR_VER from $url"
          (New-Object Net.WebClient).DownloadFile($url, $asciidoctor)
      }
      gem install --no-document --local $asciidoctor

# This section is a workaround for: https://github.com/nanomsg/nanomsg/issues/683
before_build:
  - del "C:\Program Files (x86)\MSBuild\%VS_VERSION%\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"

build:
  parallel: true
build_script:
  - cmd: IF NOT %VS_VERSION% == NONE call "C:/Program Files (x86)/Microsoft Visual Studio %VS_VERSION%/Common7/Tools/vsvars32.bat"
  - cmd: cmake --version
  - cmd: md build
  - cmd: cd build
  - cmd: cmake -G "%GENERATOR%" ..
  - cmd: cmake --build .
test_script:
  - cmd: ctest --output-on-failure -C "%CFG%"
