# CMake generated Testfile for 
# Source directory: /home/p4/src/behavioral-model/targets/simple_switch_grpc/tests
# Build directory: /home/p4/src/behavioral-model/targets/simple_switch_grpc/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Uu][Nn]_[Ss][Oo][Ll][Oo])$")
  add_test(simple_switch_grpc/test_basic "test_basic")
  set_tests_properties(simple_switch_grpc/test_basic PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/targets/simple_switch_grpc/tests/CMakeLists.txt;71;add_test;/home/p4/src/behavioral-model/targets/simple_switch_grpc/tests/CMakeLists.txt;0;")
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Uu][Nn]_[Ss][Oo][Ll][Oo])$")
  add_test(simple_switch_grpc/test_grpc_dp "test_grpc_dp")
  set_tests_properties(simple_switch_grpc/test_grpc_dp PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/targets/simple_switch_grpc/tests/CMakeLists.txt;71;add_test;/home/p4/src/behavioral-model/targets/simple_switch_grpc/tests/CMakeLists.txt;0;")
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Uu][Nn]_[Ss][Oo][Ll][Oo])$")
  add_test(simple_switch_grpc/test_packet_io "test_packet_io")
  set_tests_properties(simple_switch_grpc/test_packet_io PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/targets/simple_switch_grpc/tests/CMakeLists.txt;71;add_test;/home/p4/src/behavioral-model/targets/simple_switch_grpc/tests/CMakeLists.txt;0;")
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Uu][Nn]_[Ss][Oo][Ll][Oo])$")
  add_test(simple_switch_grpc/test_counter "test_counter")
  set_tests_properties(simple_switch_grpc/test_counter PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/targets/simple_switch_grpc/tests/CMakeLists.txt;71;add_test;/home/p4/src/behavioral-model/targets/simple_switch_grpc/tests/CMakeLists.txt;0;")
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Uu][Nn]_[Ss][Oo][Ll][Oo])$")
  add_test(simple_switch_grpc/test_meter "test_meter")
  set_tests_properties(simple_switch_grpc/test_meter PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/targets/simple_switch_grpc/tests/CMakeLists.txt;71;add_test;/home/p4/src/behavioral-model/targets/simple_switch_grpc/tests/CMakeLists.txt;0;")
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Uu][Nn]_[Ss][Oo][Ll][Oo])$")
  add_test(simple_switch_grpc/test_ternary "test_ternary")
  set_tests_properties(simple_switch_grpc/test_ternary PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/targets/simple_switch_grpc/tests/CMakeLists.txt;71;add_test;/home/p4/src/behavioral-model/targets/simple_switch_grpc/tests/CMakeLists.txt;0;")
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Uu][Nn]_[Ss][Oo][Ll][Oo])$")
  add_test(simple_switch_grpc/test_pre "/home/p4/src/behavioral-model/tests/test_pre")
  set_tests_properties(simple_switch_grpc/test_pre PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/targets/simple_switch_grpc/tests/CMakeLists.txt;71;add_test;/home/p4/src/behavioral-model/targets/simple_switch_grpc/tests/CMakeLists.txt;0;")
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Uu][Nn]_[Ss][Oo][Ll][Oo])$")
  add_test(simple_switch_grpc/test_digest "test_digest")
  set_tests_properties(simple_switch_grpc/test_digest PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/targets/simple_switch_grpc/tests/CMakeLists.txt;71;add_test;/home/p4/src/behavioral-model/targets/simple_switch_grpc/tests/CMakeLists.txt;0;")
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Uu][Nn]_[Ss][Oo][Ll][Oo])$")
  add_test(simple_switch_grpc/test_idle_timeout "test_idle_timeout")
  set_tests_properties(simple_switch_grpc/test_idle_timeout PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/targets/simple_switch_grpc/tests/CMakeLists.txt;71;add_test;/home/p4/src/behavioral-model/targets/simple_switch_grpc/tests/CMakeLists.txt;0;")
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Uu][Nn]_[Ss][Oo][Ll][Oo])$")
  add_test(simple_switch_grpc/test_action_profile "test_action_profile")
  set_tests_properties(simple_switch_grpc/test_action_profile PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/targets/simple_switch_grpc/tests/CMakeLists.txt;71;add_test;/home/p4/src/behavioral-model/targets/simple_switch_grpc/tests/CMakeLists.txt;0;")
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Uu][Nn]_[Ss][Oo][Ll][Oo])$")
  add_test(simple_switch_grpc/test_optional "test_optional")
  set_tests_properties(simple_switch_grpc/test_optional PROPERTIES  _BACKTRACE_TRIPLES "/home/p4/src/behavioral-model/targets/simple_switch_grpc/tests/CMakeLists.txt;71;add_test;/home/p4/src/behavioral-model/targets/simple_switch_grpc/tests/CMakeLists.txt;0;")
endif()
