name: Automated Release

on:
  workflow_dispatch:
  schedule:
    - cron: "17 12 1 * *" # At 12:17 on day-of-month 1 (avoid top-of-hour load)

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    # Check if the event is not triggered by a fork
    if: ${{ github.repository == 'p4lang/behavioral-model' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          # Fetch all history for all branches and tags
          fetch-depth: 0

      - name: Check for new commits
        id: check_commits
        run: |
          TAG="$(git describe --tags --abbrev=0 2>/dev/null || git rev-list --max-parents=0 HEAD)"
          COMMIT_COUNT="$(git rev-list $TAG..HEAD --count)"
          echo "count=$COMMIT_COUNT" >> $GITHUB_OUTPUT
          if [ "$COMMIT_COUNT" -eq 0 ]; then
            echo "No new commits since $TAG, skipping release."
          else
            echo "$COMMIT_COUNT new commits since $TAG."
          fi

      - name: Increment version number
        if: steps.check_commits.outputs.count != '0'
        run: perl -i -pe 's/\b(\d+)(?=\D*$)/$1+1/e' VERSION

      - name: Get changelog
        if: steps.check_commits.outputs.count != '0'
        id: changelog
        run: |
          TAG="$(git describe --tags --abbrev=0 2>/dev/null || git rev-list --max-parents=0 HEAD)"
          GIT_LOG="$(git log $TAG..HEAD --oneline --pretty=format:"- %s [%an]")"
          CHANGELOG=$(cat << EOF
          Changelog:
          $GIT_LOG
          EOF
          )
          CHANGELOG="${CHANGELOG//'#'/''}"
          echo "content<<EOF" >> "$GITHUB_OUTPUT"
          echo "$CHANGELOG" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Display changelog
        if: steps.check_commits.outputs.count != '0'
        run: |
          cat <<'EOF'
          ${{ steps.changelog.outputs.content }}
          EOF

      - name: Get version
        if: steps.check_commits.outputs.count != '0'
        run: |
          VERSION="$(cat VERSION)"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Get commit message
        if: steps.check_commits.outputs.count != '0'
        id: message
        run: |
          COMMIT_MSG=$(cat << 'EOF'
          Release ${{ env.VERSION }}

          ${{ steps.changelog.outputs.content }}
          EOF
          )
          echo "content<<EOF" >> "$GITHUB_OUTPUT"
          echo "$COMMIT_MSG" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Get pull request body message
        if: steps.check_commits.outputs.count != '0'
        id: body
        run: |
          MSG=$(cat << 'EOF'
          Auto-generated pull request for version ${{ env.VERSION }}.

          Please use **Squash and merge** to include the changelog in the release message.

          ${{ steps.changelog.outputs.content }}
          EOF
          )
          echo "content<<EOF" >> "$GITHUB_OUTPUT"
          echo "$MSG" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Create Pull Request
        if: steps.check_commits.outputs.count != '0'
        uses: peter-evans/create-pull-request@v8
        with:
          base: main
          add-paths: VERSION
          reviewers: fruffy, jafingerhut
          commit-message: ${{ steps.message.outputs.content }}
          signoff: false
          branch: release/${{ env.VERSION }}
          delete-branch: true
          title: Automated Release ${{ env.VERSION }}
          body: ${{ steps.body.outputs.content }}
