name: CMake Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        config:
          - name: "Basic Build"
            options: ""
          - name: "Without Thrift"
            options: "-DWITH_THRIFT=OFF"
          - name: "Without Nanomsg"
            options: "-DWITH_NANOMSG=OFF"
          - name: "With Debugger"
            options: "-DENABLE_DEBUGGER=ON"

    name: ${{ matrix.config.name }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Set executable permissions
      run: |
        chmod +x ./ci/install-thrift.sh
        chmod +x ./ci/codecov.sh
        chmod +x ./ci/install-nanomsg.sh

    - name: Install dependencies
      run: |
        # Switch to alternative mirrors
        sudo sed -i 's|http://archive.ubuntu.com/ubuntu|http://mirror.ubuntu.com/ubuntu|g' /etc/apt/sources.list
        sudo sed -i 's|http://security.ubuntu.com/ubuntu|http://mirror.ubuntu.com/ubuntu|g' /etc/apt/sources.list
        
        # Retry mechanism for apt-get update
        for i in {1..3}; do
          sudo apt-get update && break || {
            if [ $i -eq 3 ]; then
              echo "Failed to update package lists after 3 attempts"
              exit 1
            fi
            echo "Retrying apt-get update... (Attempt $i)"
            sleep 5
          }
        done
        
        # Install system dependencies with retry
        for i in {1..3}; do
          sudo apt-get install -y \
            automake \
            libgmp-dev \
            libpcap-dev \
            libboost-dev \
            libboost-test-dev \
            libboost-program-options-dev \
            libboost-system-dev \
            libboost-filesystem-dev \
            libboost-thread-dev \
            libevent-dev \
            libtool \
            flex \
            bison \
            pkg-config \
            g++ \
            libssl-dev \
            libprotobuf-dev \
            protobuf-compiler \
            cabal-install \
            ghc && break || {
            if [ $i -eq 3 ]; then
              echo "Failed to install system dependencies after 3 attempts"
              exit 1
            fi
            echo "Retrying system dependencies installation... (Attempt $i)"
            sleep 5
          }
        done

        # Install specific version of network package with retry
        for i in {1..3}; do
          cabal update && break || {
            if [ $i -eq 3 ]; then
              echo "Failed to update cabal after 3 attempts"
              exit 1
            fi
            echo "Retrying cabal update... (Attempt $i)"
            sleep 5
          }
        done
        
        for i in {1..3}; do
          cabal install network --constraint="network < 3.0" && break || {
            if [ $i -eq 3 ]; then
              echo "Failed to install network package after 3 attempts"
              exit 1
            fi
            echo "Retrying network package installation... (Attempt $i)"
            sleep 5
          }
        done

        # Install Thrift with specific constraints and retry
        for i in {1..3}; do
          cabal install thrift --constraint="network < 3.0" --constraint="base >= 4.7 && < 4.17" && break || {
            if [ $i -eq 3 ]; then
              echo "Failed to install thrift after 3 attempts"
              exit 1
            fi
            echo "Retrying thrift installation... (Attempt $i)"
            sleep 5
          }
        done

        # Set up protobuf paths
        echo "Protobuf_INCLUDE_DIR=/usr/include" >> $GITHUB_ENV
        echo "Protobuf_LIBRARIES=/usr/lib/libprotobuf.so" >> $GITHUB_ENV

        # Install other dependencies with retry
        for i in {1..3}; do
          ./ci/install-thrift.sh && break || {
            if [ $i -eq 3 ]; then
              echo "Failed to install thrift after 3 attempts"
              exit 1
            fi
            echo "Retrying thrift installation... (Attempt $i)"
            sleep 5
          }
        done
        
        for i in {1..3}; do
          ./ci/install-nanomsg.sh && break || {
            if [ $i -eq 3 ]; then
              echo "Failed to install nanomsg after 3 attempts"
              exit 1
            fi
            echo "Retrying nanomsg installation... (Attempt $i)"
            sleep 5
          }
        done
        
        sudo ldconfig

    - name: Configure and Build
      run: |
        mkdir -p build
        cd build
        cmake ${{ matrix.config.options }} ..
        cmake --build . -j$(nproc)

    - name: Test
      run: |
        cd build
        ctest --output-on-failure

  install:
    runs-on: ubuntu-22.04
    needs: build

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          automake \
          cmake \
          libgmp-dev \
          libpcap-dev \
          libboost-dev \
          libboost-test-dev \
          libboost-program-options-dev \
          libboost-system-dev \
          libboost-filesystem-dev \
          libboost-thread-dev \
          libevent-dev \
          libtool \
          flex \
          bison \
          pkg-config \
          g++ \
          libssl-dev
        ./ci/install-thrift.sh
        ./ci/install-nanomsg.sh
        sudo ldconfig

    - name: Configure, Build and Install
      run: |
        mkdir -p build
        cd build
        cmake ..
        cmake --build . -j$(nproc)
        sudo cmake --build . --target install
