name: CMake Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - name: "Basic Build"
            options: ""
          - name: "Without Thrift"
            options: "-DWITH_THRIFT=OFF"
          # FIXME: temporarily disable Without Nanomsg test
          # This test is failing to build correctly due to programs in tests
          # needing the bmapps lib which is not build when nanomsg is disabled.
          # The same problem occurs with using autoconf, except the binaries in
          # tests only get compiled when running "make check".
          # - name: "Without Nanomsg"
          #   options: "-DWITH_NANOMSG=OFF"
          - name: "With Debugger"
            options: "-DENABLE_DEBUGGER=ON"

    name: ${{ matrix.config.name }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y automake cmake libgmp-dev \
          libpcap-dev libboost-dev libboost-test-dev libboost-program-options-dev \
          libboost-system-dev libboost-filesystem-dev libboost-thread-dev \
          libevent-dev libtool flex bison pkg-config g++ libssl-dev
        bash ./ci/install-thrift.sh
        bash ./ci/install-nanomsg.sh
        sudo ldconfig

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake ${{ matrix.config.options }} ..

    - name: Build
      run: |
        cd build
        cmake --build .

    - name: Test
      run: |
        cd build
        ctest --output-on-failure

  install:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y automake cmake libgmp-dev \
          libpcap-dev libboost-dev libboost-test-dev libboost-program-options-dev \
          libboost-system-dev libboost-filesystem-dev libboost-thread-dev \
          libevent-dev libtool flex bison pkg-config g++ libssl-dev
        bash ./ci/install-thrift.sh
        bash ./ci/install-nanomsg.sh
        sudo ldconfig

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake ..

    - name: Build and Install
      run: |
        cd build
        cmake --build .
        sudo cmake --build . --target install
