name: CMake Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        config:
          - name: "Basic Build"
            options: ""
          - name: "Without Thrift"
            options: "-DWITH_THRIFT=OFF"
          - name: "Without Nanomsg"
            options: "-DWITH_NANOMSG=OFF"
          - name: "With Debugger"
            options: "-DENABLE_DEBUGGER=ON"

    name: ${{ matrix.config.name }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Set executable permissions
      run: |
        chmod +x ./ci/install-thrift.sh
        chmod +x ./ci/codecov.sh
        chmod +x ./ci/install-nanomsg.sh

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          automake \
          libgmp-dev \
          libpcap-dev \
          libboost-dev \
          libboost-test-dev \
          libboost-program-options-dev \
          libboost-system-dev \
          libboost-filesystem-dev \
          libboost-thread-dev \
          libevent-dev \
          libtool \
          flex \
          bison \
          pkg-config \
          g++ \
          libssl-dev
        ./ci/install-thrift.sh
        ./ci/install-nanomsg.sh
        sudo ldconfig

    - name: Configure and Build
      run: |
        mkdir -p build
        cd build
        cmake ${{ matrix.config.options }} ..
        cmake --build . -j$(nproc)

    - name: Test
      run: |
        cd build
        ctest --output-on-failure

  install:
    runs-on: ubuntu-22.04
    needs: build

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          automake \
          cmake \
          libgmp-dev \
          libpcap-dev \
          libboost-dev \
          libboost-test-dev \
          libboost-program-options-dev \
          libboost-system-dev \
          libboost-filesystem-dev \
          libboost-thread-dev \
          libevent-dev \
          libtool \
          flex \
          bison \
          pkg-config \
          g++ \
          libssl-dev
        ./ci/install-thrift.sh
        ./ci/install-nanomsg.sh
        sudo ldconfig

    - name: Configure, Build and Install
      run: |
        mkdir -p build
        cd build
        cmake ..
        cmake --build . -j$(nproc)
        sudo cmake --build . --target install
