name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check-changes:
    name: Check whether tests need to be run based on diff
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: antrea-io/has-changes@v2
      id: check_diff
      with:
        paths-ignore: docs/* *.md
    outputs:
      has_changes: ${{ steps.check_diff.outputs.has_changes }}

  test:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.has_changes == 'yes' }}
    runs-on: ${{ matrix.os }}
    name: test (${{ matrix.os }}, ${{ matrix.cc }})
    strategy:
      matrix:
        include:
        - os: ubuntu-22.04
          cxx: g++
          cc: gcc
          gcov: gcov
        - os: ubuntu-22.04
          cxx: clang++
          cc: clang
          gcov: ""
        - os: ubuntu-24.04
          cxx: g++
          cc: gcc
          gcov: gcov
        - os: ubuntu-24.04
          cxx: clang++
          cc: clang
          gcov: ""
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: 'recursive'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo ./install_deps.sh
        sudo apt-get install -y lcov
        if [ "${{ matrix.cc }}" = "clang" ]; then
          sudo apt-get install -y clang
        fi
    - name: Run tests
      env:
        CC: ${{ matrix.cc }}
        CXX: ${{ matrix.cxx }}
        GCOV: ${{ matrix.gcov }}
      run: |
        ./autogen.sh
        CONFIG_FLAGS="--with-pdfixed --with-pi --with-stress-tests --enable-debugger --enable-Werror"
        if [ -n "$GCOV" ]; then
          ./configure $CONFIG_FLAGS --enable-coverage
        else
          ./configure $CONFIG_FLAGS
        fi
        make -j$(nproc)
        make check -j$(nproc)
        ./ci/codecov.sh
    - name: Check style
      run: |
        ./tools/check_style.sh

  test-no-pi:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.has_changes == 'yes' }}
    runs-on: ${{ matrix.os }}
    name: test-no-pi (${{ matrix.os }})
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: 'recursive'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo ./install_deps.sh
    - name: Run tests
      run: |
        ./autogen.sh
        ./configure --enable-debugger --enable-Werror
        make -j$(nproc)
        make check -j$(nproc)

  test-cmake:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.has_changes == 'yes' }}
    runs-on: ${{ matrix.os }}
    name: test-cmake (${{ matrix.os }})
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: 'recursive'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo ./install_deps.sh
    - name: Build BMv2
      run: |
        mkdir -p build
        cd build
        cmake -DWITH_PDFIXED=ON -DWITH_PI=ON -DWITH_STRESS_TESTS=ON -DENABLE_DEBUGGER=ON -DENABLE_WERROR=ON ..
        make -j$(nproc)
    - name: Run tests
      run: cd build && make -j$(nproc) && ctest -j$(nproc) --output-on-failure
